/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cs372_exam_derikoliver;

/**
 *
 * @author doliver17
 */
public class Under_Over extends javax.swing.JFrame {
    public static Game game = new Game();

    /**
     * Creates new form Under_Over
     */
    public Under_Over() {
        initComponents();
        Read();
    }
    
    private void Read() {
        try {
            game.Read();
        }
        catch(Exception E) {
            E.getMessage();
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();
        Prompt = new javax.swing.JLabel();
        UserName = new javax.swing.JTextField();
        EnterButton = new javax.swing.JButton();
        ChooseOutcomePrompt = new javax.swing.JLabel();
        EnterBetPrompt = new javax.swing.JLabel();
        BetValue = new javax.swing.JTextField();
        ButtonUnder7 = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        ButtonOver7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Dice1Value = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Dice2Value = new javax.swing.JTextField();
        Results = new javax.swing.JTextField();
        CurrentBalance = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Prompt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Prompt.setText("Enter Your Username");

        UserName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        UserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UserNameKeyPressed(evt);
            }
        });

        EnterButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EnterButton.setText("Enter");
        EnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterButtonActionPerformed(evt);
            }
        });

        ChooseOutcomePrompt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChooseOutcomePrompt.setForeground(new java.awt.Color(0, 153, 153));
        ChooseOutcomePrompt.setText("Choose Your Outcome");

        EnterBetPrompt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EnterBetPrompt.setForeground(new java.awt.Color(0, 153, 153));
        EnterBetPrompt.setText("Enter Your Bet");

        BetValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ButtonUnder7.setText("Under 7");
        ButtonUnder7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUnder7ActionPerformed(evt);
            }
        });

        Button7.setText("7!!!!");
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });

        ButtonOver7.setText("Over 7");
        ButtonOver7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOver7ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setText("Your Balance");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Dice 1:");

        Dice1Value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dice1ValueActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Dice 2:");

        Results.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Results.setText("Results");

        CurrentBalance.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        CurrentBalance.setForeground(new java.awt.Color(153, 0, 51));
        CurrentBalance.setText("$$$$$$$$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BetValue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnterBetPrompt))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Prompt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(ChooseOutcomePrompt)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CurrentBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ButtonUnder7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Dice1Value, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Results, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Dice2Value, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ButtonOver7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EnterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Prompt)
                    .addComponent(jLabel1)
                    .addComponent(CurrentBalance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EnterButton)
                .addGap(16, 16, 16)
                .addComponent(EnterBetPrompt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BetValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ChooseOutcomePrompt)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonUnder7)
                    .addComponent(Button7)
                    .addComponent(ButtonOver7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Dice1Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Dice2Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Results, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonUnder7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUnder7ActionPerformed
        if(game.Play(Integer.parseInt(BetValue.getText()), 0))
            Results.setText("You Won!");
        else
            Results.setText("You Lost!");
            
        Dice1Value.setText(game.getD1().toString());
        Dice2Value.setText(game.getD2().toString());
        CurrentBalance.setText(game.GetPlayerBalance().toString());
        game.Save();
    }//GEN-LAST:event_ButtonUnder7ActionPerformed

    private void EnterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterButtonActionPerformed
        String name = UserName.getText();
        game.NewPlayer(name);
        CurrentBalance.setText(game.GetPlayerBalance().toString());
    }//GEN-LAST:event_EnterButtonActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        if(game.Play(Integer.parseInt(BetValue.getText()), 1))
            Results.setText("You Won!");
        else
            Results.setText("You Lost!");
        
        Dice1Value.setText(game.getD1().toString());
        Dice2Value.setText(game.getD2().toString());
        CurrentBalance.setText(game.GetPlayerBalance().toString());
        game.Save();
    }//GEN-LAST:event_Button7ActionPerformed

    private void ButtonOver7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOver7ActionPerformed
        if(game.Play(Integer.parseInt(BetValue.getText()), 2))
            Results.setText("You Won!");
        else
            Results.setText("You Lost!");
        
        Dice1Value.setText(game.getD1().toString());
        Dice2Value.setText(game.getD2().toString());
        CurrentBalance.setText(game.GetPlayerBalance().toString());
        game.Save();
    }//GEN-LAST:event_ButtonOver7ActionPerformed

    private void UserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UserNameKeyPressed
        String name = UserName.getText();
        game.NewPlayer(name);
        CurrentBalance.setText(game.GetPlayerBalance().toString());
    }//GEN-LAST:event_UserNameKeyPressed

    private void Dice1ValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dice1ValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dice1ValueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Under_Over.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Under_Over.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Under_Over.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Under_Over.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Under_Over().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BetValue;
    private javax.swing.JButton Button7;
    private javax.swing.JButton ButtonOver7;
    private javax.swing.JButton ButtonUnder7;
    private javax.swing.JLabel ChooseOutcomePrompt;
    private javax.swing.JLabel CurrentBalance;
    private javax.swing.JTextField Dice1Value;
    private javax.swing.JTextField Dice2Value;
    private javax.swing.JLabel EnterBetPrompt;
    private javax.swing.JButton EnterButton;
    private javax.swing.JLabel Prompt;
    private javax.swing.JTextField Results;
    private javax.swing.JTextField UserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
